In [6]:
import pandas as pd

In [11]:
# 1. Charger ton fichier (csv, excel, etc.)
df = pd.read_excel("taux_voiture_menages.xlsx")
df.head()

,Équipement automobile des ménages en 2022 : comparaisons départementales,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,en %
2,NaN,NaN,Taux d’équipement des ménages,Part des ménages ayant une seule voiture,Part des ménages ayant deux voitures ou plus
3,01,Ain,91.4,44.1,47.3
4,02,Aisne,83.7,46.2,37.5

In [12]:


# 2. Définir la liste des départements d'Île-de-France (en chaînes de caractères)
idf_deps = ['75', '77', '78', '91', '92', '93', '94', '95']

In [14]:
# On garde toutes les lignes à partir de l'indice 3 jusqu'à la fin
df = df.iloc[3:]

# On réinitialise les index pour que ça reparte de 0
df = df.reset_index(drop=True)

df.head()

,Équipement automobile des ménages en 2022 : comparaisons départementales,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,01,Ain,91.4,44.1,47.3
1,02,Aisne,83.7,46.2,37.5
2,03,Allier,85.5,47.2,38.3
3,04,Alpes-de-Haute-Provence,88.6,50.1,38.5
4,05,Hautes-Alpes,88.8,50.5,38.3

In [32]:
# On remplace 'Ancien Nom' par 'Departement', etc.
df = df.rename(columns={
    'Équipement automobile des ménages en 2022 : comparaisons départementales': 'code_Commune', 
    'Unnamed: 1': 'departement',
    'Unnamed: 2': '',
    'Unnamed: 3': 'taux_equipement_menages',
    'Unnamed: 4': 'part_menages_voiture',
    'Unnamed: 5': 'part_menages_voitures',

})

df.head()

,Code_Commune,code_departement,departement,taux_equipement_menages,part_menages_voiture
0,75,Paris,31.8,27.9,3.8
1,77,Seine-et-Marne,85.1,46.9,38.2
2,78,Yvelines,83.4,49.9,33.5
3,91,Essonne,82.9,48.7,34.2
4,92,Hauts-de-Seine,62.7,48.7,14

In [22]:
# 3. Filtrer les données
# On suppose que ta colonne s'appelle 'code_postal' ou 'departement'
# On prend les 2 premiers chiffres du code postal pour comparer
df_idf = df[df['Code_Commune'].astype(str).str.startswith(tuple(idf_deps))]

In [23]:

# 4. Vérifier le résultat
print(f"Nombre de lignes restantes : {len(df_idf)}")
df_idf.head()

Nombre de lignes restantes : 8

,Code_Commune,code_departement,departement,taux_equipement_menages,part_menages_voiture
75,75,Paris,31.8,27.9,3.8
77,77,Seine-et-Marne,85.1,46.9,38.2
78,78,Yvelines,83.4,49.9,33.5
91,91,Essonne,82.9,48.7,34.2
92,92,Hauts-de-Seine,62.7,48.7,14

In [24]:
df.info(100)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Code_Commune             104 non-null    object
 1   code_departement         102 non-null    object
 2   departement              102 non-null    object
 3   taux_equipement_menages  102 non-null    object
 4   part_menages_voiture     102 non-null    object
dtypes: object(5)
memory usage: 4.2+ KB

In [25]:
# Exemple si ta colonne s'appelle 'code_dept'
idf = ['75', '77', '78', '91', '92', '93', '94', '95']
df_idf = df[df['Code_Commune'].astype(str).isin(idf)]

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Code_Commune             104 non-null    object
 1   code_departement         102 non-null    object
 2   departement              102 non-null    object
 3   taux_equipement_menages  102 non-null    object
 4   part_menages_voiture     102 non-null    object
dtypes: object(5)
memory usage: 4.2+ KB

In [28]:
df.to_csv("menage.csv", index=False)

In [30]:
# 1. On définit la liste des départements d'Île-de-France
# Note : on les met entre guillemets car ce sont souvent des textes (surtout pour le 75, 77, etc.)
idf = ['75', '77', '78', '91', '92', '93', '94', '95']

# 2. On ne garde que les lignes où la colonne 'Departement' est dans notre liste
df = df[df['Code_Commune'].astype(str).isin(idf)]

# 3. On réinitialise l'index pour que ça reparte de 0, 1, 2...
df = df.reset_index(drop=True)

# 4. On vérifie le résultat
print(f"Il reste {len(df)} lignes pour l'Île-de-France.")
df.head()

Il reste 8 lignes pour l'Île-de-France.

,Code_Commune,code_departement,departement,taux_equipement_menages,part_menages_voiture
0,75,Paris,31.8,27.9,3.8
1,77,Seine-et-Marne,85.1,46.9,38.2
2,78,Yvelines,83.4,49.9,33.5
3,91,Essonne,82.9,48.7,34.2
4,92,Hauts-de-Seine,62.7,48.7,14

In [31]:
df.to_csv("code_menages.csv", index=False)

In [45]:
# On crée une copie de la liste des colonnes actuelles
cols = list(df.columns)

# On modifie uniquement l'élément à l'index 1 (la 2ème colonne)
cols[4] = "part_menages_des_voitures"

# On réassigne la liste modifiée au DataFrame
df.columns = cols

# On vérifie le changement
df.head()

,Code_Commune,departement,taux_equipement_menages,part_menages_une_voiture,part_menages_des_voitures
0,75,Paris,31.8,27.9,3.8
1,77,Seine-et-Marne,85.1,46.9,38.2
2,78,Yvelines,83.4,49.9,33.5
3,91,Essonne,82.9,48.7,34.2
4,92,Hauts-de-Seine,62.7,48.7,14

In [46]:
df.to_csv("code_menage.csv", index=False)

In [ ]:

df = df.rename(columns={
    'part_menages_voiture': 'part_menages_voituret',
})

df.head()